### ISSUE TITLE
Localization "Start typing language name"

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#119]
1) Open http://lingvodoc.ispras.ru
2) Select Russian language
Expected: "Start typing language name" should be localized. 
Actual: Message (placeholder) is not localized.
![image](https://user-images.githubusercontent.com/59951991/72527661-50252a80-387a-11ea-9905-55cb35e988cb.png)

**Comment by nadezhday** [comment]
There are a lot of places where we have the same localization problem (placeholders). It would be nice to fix it in this work item.
1) Login dialog
![image](https://user-images.githubusercontent.com/59951991/72527956-fa9d4d80-387a-11ea-943e-46fb49b7601f.png)

**Comment by al-indigo** [comment]
@jandrew44 convert it please to translatable strings and I will add the translations for them

**Comment by jandrew44** [comment]
The following has been done:

1) Improved the general way of language selection, so that translations appear right after switching the language now.
2) Fixed problems mentioned in this work item(main page and sign in dialog).
Translation strings exists already, there is no need to add it.
3) Fixed similar problem in user registration dialog.

**Comment by nadezhday** [comment]
Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_localization.py
