### ISSUE TITLE
Implement [x] close button on the top in all dialogs

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#128]
-Open http://lingvodoc.ispras.ru/dictionary/2639/4263/perspective/2639/4267/view
-Open any dialog (e.g. Click Lexical Entries->'Lexical Entries' statistics...)
It would be nice to add [x] button on the top of the dialogs so user will not need to scroll down the dialog to press Cancel button.
![image](https://user-images.githubusercontent.com/59951991/72594690-19522180-3919-11ea-93bc-5ee636ac2f1a.png)

-Click Show statictics button
![image](https://user-images.githubusercontent.com/59951991/72594871-9382a600-3919-11ea-88a4-7f473f8c1239.png)

Problem: Cancel button is not visible in the dialog.
So it would be good to have [x] on the top to close this dialog. 
Right now the user will have to scroll the dialog to find Cancel button. - NOK

**Comment by al-indigo** [comment]
@myrix if you don't know how to do it, reassign it to Alex or Andrew please

**Comment by myrix** [comment]
Added close icon to almost all modal dialogs that do not have it already:

1. Statistics.
2. Roles.
3. Create field.
4. Markup.
5. Convert EAF.
6. Player.
7. Create organization.
8. Dictionary properties.
9. Perspective properties.
10. Cognate analysis.
11. Phonology.
12. Save dictionary.
13. User -> User account activation / deactivation.
14. User -> Sign in.
15. User -> Sign up.
16. User -> Edit profile.
17. Phonemic analysis.
18. Search -> Advanced search -> Select languages.
19. Search -> Advanced search -> Grammar.
20. Search -> Advanced search -> Select tags.
21. Search results -> Blobs.
22. Search results -> Blobs -> View Blob.
23. Starling import -> Language selection.

Left entity image viewing dialog unchanged, without close icon, because the dialog contains only the image being viewed and close icon would overlap it, preventing user from seeing part of it.

See e.g. http://lingvodoc.ispras.ru/dictionary/671/15154/perspective/748/553/view, filter search "три человека", field "Praat markup", button "View".

Note: both that dialog and all dialogs mentioned above, except for Dictionary properties dialog, can be closed by standard Esc keyboard key press or mouse click on the dimmer outside the dialog. Dictionary properties dialog can still be closed by Esc keyboard key press.

**Comment by nadezhday** [comment]
Verified.

1.  Statistics. - OK
2.     Roles. - OK
3.     Create field. (Lexical properties->dropdown menu->add new field...) - OK
4.     Markup. - OK
5.     Convert EAF.  -OK
(Open http://83.149.198.62/dictionary/1232/8789/perspective/1232/8792/view 
![image](https://user-images.githubusercontent.com/59951991/73435619-0ea47d00-435a-11ea-8bcc-d5d088f3e2ee.png)

6.     Player. (Sound column and click Play button) - OK
7.     Create organization. - OK
8.     Dictionary properties. - NOK (Minor issue. Bug will not be created)
[x] is located inside sigment. 
![image](https://user-images.githubusercontent.com/59951991/73434455-d4d27700-4357-11ea-9acb-3955d30ee5c8.png)

9.     Perspective properties. (My dictionaries-> dropdown menu 'Perspective'->properties) - OK
10.     Cognate analysis. Tools->.. - OK
11.     Phonology. Tools->.. - OK 
12.     Save dictionary. -OK
![image](https://user-images.githubusercontent.com/59951991/73434217-5d044c80-4357-11ea-871b-efc2c1011b9e.png)

13.     User -> User account activation / deactivation. - OK
14.     User -> Sign in. - OK
15.     User -> Sign up. - OK
16.     User -> Edit profile. - OK
17.     Phonemic analysis. Tools->.. -OK
18.     Search -> Advanced search -> Select languages. -OK
19.     Search -> Advanced search -> Grammar. - OK
20.     Search -> Advanced search -> Select tags. - OK
21.     Search results -> Blobs. OK
22.     Search results -> Blobs -> View Blob. - OK
23.     Starling import -> Language selection. - OK
