### ISSUE TITLE
Close dialogs by clicking on [x] or Close button.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#131]
-Open http://lingvodoc.ispras.ru/ 
-Click User->Sign Up
![image](https://user-images.githubusercontent.com/59951991/72610637-f5063d00-3938-11ea-8cda-908d924129a2.png)
-Fill in data (name etc).
-Click outside sign up dialog 
![image](https://user-images.githubusercontent.com/59951991/72610822-7eb60a80-3939-11ea-8fa3-f41eb28347a2.png)

Usability problem: Dialog closes and you have to repeat all above steps again. 
The same problem with Sign In dialog.

**Comment by al-indigo** [comment]
1. Don't think that's an issue, since it clears sensitive data: users often use public computers for work. If someone in distraction would "almost login" and close it, someone else could intercept his login token (or even a password if the browser is not set up for public usage).
2. It may be a feature of the framework also

**Comment by nadezhday** [comment]
OK. We can close this issue.
