### ISSUE TITLE
Improvements in ordering paradigms

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#256]
Custom request:

1) Подскажите, пожалуйста, нельзя ли в Лингводоке парадигмы слова упорядочить? Хотелось бы, чтобы  формы шли по порядку, например, "я вижу", "ты видишь", "он видит" и т.д. Загружаю в таком порядке, но в итоге, когда открываешь парадигмы лексического входа, все формы в разброс получаются все равно

2) Нельзя ли, например, сделать так, чтобы парадигмы отображались в таком порядке, в каком их связываешь с лексическим входом?

Но точно ли именно в порядке связывания? Может, если нужен какой-то порядок, не лучше ли будет показывать просто в порядке создания парадигм в их перспективе? Это проще и кажется не так произвольно, как порядок связывания.

В словаре http://lingvodoc.ispras.ru/dictionary/3080/30/perspective/3080/34/edit?page=2 можете посмотреть парадигмы слова "беречь, оберегать"

Если будет сделано, то будет отображаться в порядке создания лекс. входов в соответствующей Paradigm-перспективе, http://lingvodoc.ispras.ru/dictionary/3080/30/perspective/3080/38/edit, т.е. если туда добавлять в определенном порядке, то будет этот этот порядок.

Или можно подумать насчет добавления в диалог отображения парадигм возможность сортировки по полям, чтобы например можно было показывать в порядке переводов Translation of paradigmatic forms

Иконки сортировки рядом с именами полей, как в отображении перспективы.
Или сортировка по времени создания в Paradigms достаточна?

Думаю, по умолчанию, сортировка по времени создания будет оптимальным вариантом. Но, может, кому-то и по переводам будет проще искать (наверное, тоже можно добавить)

**Comment by myrix** [comment]
For now we are going to implement sorting of paradigm lexical entries by their creation time.

Testing scenario: open http://83.149.198.62/dictionary/657/3/perspective/657/4/view, search for word "армия", open its "Paradigm and contexts" field info, open paradigms link, we have following paradigm lexical entries:
![image](https://user-images.githubusercontent.com/2802467/86583405-df8adb00-bf8b-11ea-83d0-71f0b7a37472.png)

When sorting is implemented, these lexical entries should appear in the creation time order.

**Comment by myrix** [comment]
Implemented sorting.

It should be noted that in the test case mentioned above, and probably in many other cases, if not the most, paradigm lexical entries had already been shown in creation time order, probably due to implicit database retrieval ordering corresponding to database storage ordering in turn corresponding to creation ordering; now sorting is explicitly by creation time.

Test case now:
![image](https://user-images.githubusercontent.com/2802467/86585754-9d639880-bf8f-11ea-8bfa-7ede06106a80.png)

**Comment by pavel-ho** [comment]
as I understand it,
this issue consists of two parts

1. So that in the paradigms view of a given lexical entry they are displayed in the order they were created in the paradigms perspective

2. so that in the paradigms display for a given lexical entry it was possible to sort by fields ('Translation of paradigmatic forms' and all others)

**Comment by myrix** [comment]
Sorting by fields would probably be a separate issue, so we can treat this one as only about the sorting by creation time.

**Comment by pavel-ho** [comment]
The first part verified:

in http://83.149.198.62/dictionary/657/3/perspective/657/10/edit
added paradigms in the orderfirst second third forth

in http://83.149.198.62/dictionary/657/3/perspective/657/4/edit
in the word "армия" linked (Paradigms and context -> Add link) paradigms in the order third forth second one
After that they are displayed in the creation order - first second third forth

**Comment by pavel-ho** [comment]
New issue https://github.com/ispras/lingvodoc-react/issues/261 created

**Comment by pavel-ho** [comment]
Covered in Selenium tests
