### ISSUE TITLE
Distance map: Dots on the Map do not have any titles.

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#292]
Issue is found during testing #275 Phonetic proximity on the map

steps to reproduce:
![image](https://user-images.githubusercontent.com/59951991/93432835-be6d3180-f8ce-11ea-9805-7da38a0420cf.png)
-Open http://83.149.198.62/distance_map
- Find Dictionary Upper Pelym dialect of Mansi language, author priest K.Slovcov, 1905 (Ю.В.Норманская)
- click Select dictionary
- Add dictionaries of other language groups
-Uralic, Mansi, Easten
-select option ON for dictionary Dictionary of Yukonda dialect of Mansi
-Next

Problem: Dots on the Map do not have any titles. 
![image](https://user-images.githubusercontent.com/59951991/93433790-f5901280-f8cf-11ea-8a29-f3403b958c51.png)
It is user-unfriendly.

**Comment by elmedweb** [comment]
Clarify, no constantly or when pointing at a point? When the bug is reproduced, the inscription is displayed. It was discussed that this will work when pointing the mouse
![Screenshot from 2020-09-18 03-58-31](https://user-images.githubusercontent.com/40824202/93663788-7ac42480-fa94-11ea-9c25-7d4186496a97.png)

**Comment by nadezhday** [comment]
Backend:
2.1.1+1232-b95b85a9-2020.09.21-06:37+modified-2020.09.21-16:35
Frontend:
06faa11a-371-staging-server

Works OK.
![image](https://user-images.githubusercontent.com/59951991/93848786-3ebada80-fcb3-11ea-9397-652d4f0a0fcd.png)

**Comment by nadezhday** [comment]
covered in selenium test
