### ISSUE TITLE
Properties for corpus with new metadata are empty

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#315]
Backend:
2.1.1+1228-bcdde400-2020.09.14-05:34+modified-2020.09.19-16:18

Frontend:
0.0.1+327-2b3a7a88-369-staging-server

create corpus 
![image](https://user-images.githubusercontent.com/59951991/93742007-0dc8a000-fbf6-11ea-8647-8dcfb055dbb4.png)

Open it
![image](https://user-images.githubusercontent.com/59951991/93742052-246ef700-fbf6-11ea-906e-b0c95aaa1379.png)

Invoke properties
![image](https://user-images.githubusercontent.com/59951991/93741843-ccd08b80-fbf5-11ea-8cfa-3ed34dd591b1.png)

Problem:
1)Properties are empty
![image](https://user-images.githubusercontent.com/59951991/93741723-9f83dd80-fbf5-11ea-9981-1b4aadf53320.png)
2) try to modify and save changes
Problem it is not possible
![image](https://user-images.githubusercontent.com/59951991/93742175-5a13e000-fbf6-11ea-9e51-5828bad2c2d7.png)

**Comment by nadezhday** [comment]
Problem was found during testing https://github.com/ispras/lingvodoc-react/issues/284 Corpus metadata

**Comment by jandrew44** [comment]
Dictionary metadata properties were displayed instead of corpus ones, I have fixed this problem.
However, corpus metadata properties cannot be queried from backend because they are missing in the MetaData type.
@myrix these fields needs to be added there: titleOfTheWork, genre, timeOfWriting, quantitativeCharacteristic, bibliographicDataOfTheSource, translator, bibliographicDataOfTheTranslation.

**Comment by myrix** [comment]
@jandrew44 fields added.

**Comment by jandrew44** [comment]
Fixed.

**Comment by nadezhday** [comment]
Verified

**Comment by vmonakhov** [comment]
Covered in tests/test_dashboard_create_corpus.py
