### ISSUE TITLE
Failed to compute cognate analysis: GraphQL error

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#440]
test case test_cognate_suggestions.py: test_lex_cognate_sugg_unselect_match - FAIL

steps to reproduce:
login as admin
search for Dictionary of Livvik dialect in Finland
Open Lexial view
Toos->Cognate_suggestions
deselect Match transtlations checkbox
Click Cognate

Expected: Analysis results
Actual: Failed to compute cognate analysis
![image](https://user-images.githubusercontent.com/59951991/109793886-46998600-7c26-11eb-99a1-a9815e7d8986.png)

**Comment by nadezhday** [comment]
@yesandv FYI

**Comment by myrix** [comment]
@nadezhday 

Checked locally, computes ok:
![image](https://user-images.githubusercontent.com/2802467/109796745-97f74480-7c29-11eb-897c-52b94add08a7.png)

It seems the problem is that due to a large number of source data the size of buffers requested by the liboslon.so library, which performs the computation, is too big, about 14 GB of virtual memory, and, more importantly, server memory consumption peaks at about something more than 6 GB of resident memory.

So, the solution is either to increase test stand's available RAM, or to contact Mikhail Oslon about possible memory optimizations of liboslon.so library (piecemeal data consumption, something else?), but I think the second option is unlikely as, as far as I know, Mikhail Oslon does not actively work on liboslon.so anymore.

**Comment by nadezhday** [comment]
Reise SkipTest.
As soon as we increase test stand's RAM etc we will make our test available again.

**Comment by myrix** [comment]
Works ok in latest tests.

**Comment by yesandv** [comment]
Verified.
