### ISSUE TITLE
Edit interface translations: Duplicated gists

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#552]
Login as admin
Tools > Edit interface translations
Perspective

Problem: why do we have so many duplicated gists?

Will we do anything about it (hide)?

![image](https://user-images.githubusercontent.com/59951991/146516440-390f8e2b-9c23-4d5e-a513-d98273871945.png)

**Comment by nataliauvarova** [comment]
such data comes from the backend,
it will not be possible to hide them.

**Comment by nadezhday** [comment]
@myrix can (should) we do anything about this?

**Comment by myrix** [comment]
> @myrix can (should) we do anything about this?

Looks like these gists are just representing the same names of different perspectives or different dictionaries, so I don't think we should do anything about it.

Given that these gists are perspectives' names, should we even edit them in this admin tools? If you want to edit perspective's names, just go to it's properties page and edit it, otherwise you risk editing the wrong name. And the same with dictionaries' names in the "Dictionary" tab.

**Comment by nadezhday** [comment]
Closing as Works As Design.
