### ISSUE TITLE
Edit interface translations: Performance problem

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#563]
Login as admin
Tools > Edit interface translations
Dictionary (All)

We have problem with performance.

It takes about 5 sec to load all information - NOK

**Comment by nadezhday** [comment]
It is almost impossible to work with this feature.

**Comment by jandrew44** [comment]
There are just too many entities.
In order to solve such performance issues backend need to support pagination in its queries.
Note it is required in many places, not on this page only.
For example, lexical entries table in dictionaries has the same problem(in case of many lexical entries).
For some of such queries backend should support filtering and sorting also.
@myrix FYI, it is a large general task for backend(not urgent).

**Comment by jandrew44** [comment]
Solved by the backend pagination already.

**Comment by vmonakhov** [comment]
Works good. Verified.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py exactly this case
