### ISSUE TITLE
Parser variants edition allowed

### ISSUE THREAD

**Issue by ankan2013** [ispras/lingvodoc-react#596]
A pull request https://github.com/ispras/lingvodoc-react/pull/589 was made to allow a user edit not only user's variants, but also variants made by a parser.
Steps for testing:
1) make everything described at https://github.com/ispras/lingvodoc-react/issues/595
2) select a word highlighted with red color (e.g. 'саха') and press the violet button ('edit') at one of its variants at the 'Proposed variants' panel:
![Screenshot from 2022-01-24 14-00-39](https://user-images.githubusercontent.com/45983282/150773914-64573af3-b976-4f84-82db-03d17f4b417c.png)
3) Fill all fields of the form:
![Screenshot from 2022-01-24 14-01-37](https://user-images.githubusercontent.com/45983282/150773984-32ca5c80-64b3-423a-94e8-0700c7d107a6.png)
and press save, after that the variant should look like:
![Screenshot from 2022-01-24 14-01-45](https://user-images.githubusercontent.com/45983282/150774088-d10c2fe1-6472-4409-bae8-4870cac1dcdf.png)
4) Also, a variant can be deleted by pressing a red button: after pressing it and the confirmation of the deletion the variant should disappear.

**Comment by nadezhday** [comment]
Buttons Edit, Delete have been implemented OK
Confirmation for deletion - OK
![image](https://user-images.githubusercontent.com/59951991/151133586-80e9502e-edce-4edd-a311-2ca6daaf4437.png)

Dialog User defined variant opens. - OK
Data is saved - OK

![image](https://user-images.githubusercontent.com/59951991/151133884-232344b9-8264-4470-9366-ab72bc6fdebd.png)

Note: Because ALL fields are required you will never get back to initial (empty) state.

Separate critical defect is created:
Impossible to use digits, ARROW RIGHT and ARROW LEFT in User defined variant dialog.  
https://github.com/ispras/lingvodoc-react/issues/602

**Comment by nadezhday** [comment]
This case can be verified
Covered in tests\test_parser_sah.py
