### ISSUE TITLE
Translation cache bug

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#599]
Open /edit_translations logged in as admin, change a Russian version of some translation gist, e.g. of "Cognate analysis" to e.g. "Анализ когнатов ИЗМЕНЕНО", save changes, check (e.g. by opening 'Инструменты' in /dictionary/657/3/perspective/657/4/view) that Russian translation in the interface has not changed.

**Comment by myrix** [comment]
Fixed, now translations in the interface change as expected.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/151107795-f8ef6c27-2989-4965-aa9b-c3892cd8b913.png)

**Comment by nadezhday** [comment]
This is the left problem from https://github.com/ispras/lingvodoc-react/issues/580
Now the problem is fixed

![image](https://user-images.githubusercontent.com/59951991/151108001-4af4126a-a21e-40f3-8821-b778a948bf34.png)

Verified here: http://lingvodoc.ispras.ru/dictionary/657/3/perspective/657/4/view

**Comment by nadezhday** [comment]
http://83.149.198.62/dictionary/4467/4/perspective/4467/7/edit

![image](https://user-images.githubusercontent.com/59951991/151150151-9a3991e7-fb46-4490-ae0c-5c2ff7b9be36.png)

Separate case
Cognate suggestions (disabled, perspective is not published)
Cognate multi-language suggestions (disabled, perspective is not published)

https://github.com/ispras/lingvodoc-react/issues/605  Localization Cognate commands (disabled, perspective is not published)
