### ISSUE TITLE
Page with organizations

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#629]
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=1927%3A7720

Change the design of the page with organizations

**Comment by nataliauvarova** [comment]
Done this page with a new design.

Added the "Organization" tab to the page http://lingvodoc.ru/edit_translations to add translations for the names and descriptions of organizations.

The names of Members and Admins of organizations are currently impossible to localize. Because there is no such functionality on the Lingvodoc project.

Localization for Create organization dialog  will be done here: https://github.com/ispras/lingvodoc-react/issues/618

**Comment by nadezhday** [comment]
Realization of Add organization dialog and its localization will be done here: https://github.com/ispras/lingvodoc-react/issues/618 [Create organization dialog and its localization](https://github.com/ispras/lingvodoc-react/issues/618#)

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/156871768-9de71176-58ad-4787-8319-60f7be2573b8.png)

@nataliauvarova  @al-indigo, FYI
Should we add a possibility to delete a member from Organization.
https://github.com/ispras/lingvodoc-react/issues/637 Possibility to delete a member from Organization

Should we have a fixed order in the Organization table?
https://github.com/ispras/lingvodoc-react/issues/638 Ordering in Organization table

**Comment by nadezhday** [comment]
Covered in tests\test_organization_admins.py
