### ISSUE TITLE
Tasks: Clear completed does not work

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#670]
login as admin
http://83.149.198.62/dictionary/4351/15/perspective/4351/18/edit 
click button to start Reparsing 

![image](https://user-images.githubusercontent.com/59951991/159878165-6a4dfae2-3cc4-446c-b6aa-edbcba3275b6.png)

Open Tasks

After Process finishes Click Clear completed button.

Expected: Task view is empty

Actual: Clear completed button is not available.

**Comment by jandrew44** [comment]
@myrix have you changed something related to reparsing tasks on the backend recently?
For this scenario, there is no change in the task.status field of the reparsing task(it does not set to "Finished" when the task is done).
However, progress field is set to 100 but I am not sure if it can be used as criteria of completed task.

**Comment by myrix** [comment]
@jandrew44 didn't change anything, final status of reparsing task was always like that ever since it was introduced some 4 months ago.

In general, there is no guidelines on task statuses, so I propose that the 'finished' condition to be checked as a progress of 100 at the last stage; and that this to be enforced for all tasks on backend's side.

**Comment by nadezhday** [comment]
Verified.
Now it works fine.
![image](https://user-images.githubusercontent.com/59951991/160115766-690b7717-a8dd-4eae-8cff-447a15780032.png)

**Comment by vmonakhov** [comment]
Covered in tests/test_parser_reparsing.py
