### ISSUE TITLE
In dictionaries, leave only the table of contents.

### ISSUE THREAD

**Issue by Dina936** [ispras/lingvodoc-react#720]
Learn more at Figma:
https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=610%3A5982

**Comment by myrix** [comment]
Implemented, works.

Changed "Languages databases" to "Language databases" in the translations at http://lingvodoc.ispras.ru/ as required by the changes.

@nataliauvarova Please check the details of the design, modify if required and then close when good.

There is one intentional difference with the design, instead of a list of perspectives, like "Lexical Entries, Paradigms" after dictionary name, there is a dropdown menu activated by a click on the dictionary name, as discussed with Dina.

**Comment by Dina936** [comment]
In dictionaries, now "lexical entries" and "paradigms" are opened by clicking on the dictionary.
You need to put these items at the end of the dictionary so that they are immediately visible.
<img width="451" alt="Снимок экрана 2022-07-05 в 13 51 58" src="https://user-images.githubusercontent.com/56397844/177317969-662fc45b-2b59-4093-8f82-38a1e7bf9e31.png">

https://www.figma.com/file/YEcJISLZlXPqAFfHhS8Q2o/Lingvodoc?node-id=610%3A5982

**Comment by Dina936** [comment]
when you hover over a dictionary, change the state to make it clear that it is clickable
<img width="484" alt="Снимок экрана 2022-07-05 в 16 33 31" src="https://user-images.githubusercontent.com/56397844/177341229-1d4724a5-6450-4449-84d7-631216289375.png">

**Comment by nataliauvarova** [comment]
fixed
