### ISSUE TITLE
Cognate acoustic analysis: Exception (Uncaught (in promise) TypeError: a is undefined)

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#725]
Test tests\test_cognate_acoustic_analysis.py - FAILed
Login as Julia
Open /dictionary/657/3/perspective/657/4/view
Tools - Cognate acoustic analysis

Problem: Exception

![image](https://user-images.githubusercontent.com/59951991/164605755-5dfc0aea-d9e1-4a20-8d36-4bc2643a290d.png)

**Comment by nadezhday** [comment]
Actually we have problems with Tools:
1)cognate_multi_analysis
2)cognate_multi_reconstr
3)cognate_multi_suggestions

**Comment by myrix** [comment]
Seems related to #718.

**Comment by myrix** [comment]
Probably not because of #718, more likely because of upgrades of react, redux and apollo.

Fixed, now Cognate analysis, Cognate acoustic analysis, Cognate multi-language analysis, Cognate reconstruction, Cognate multi-language reconstruction, Cognate suggestions and Cognate multi-language suggestions open and compute ok.

**Comment by nadezhday** [comment]
Manual testing: OK
Automatic tests - OK
