### ISSUE TITLE
Translation: Regular expressions functionality works incorrectly

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#737]
Initially type: perspective
![image](https://user-images.githubusercontent.com/59951991/165039041-6072f960-4614-48c6-b30f-c86e65c71ae3.png)

1)  type: perspective*9
![image](https://user-images.githubusercontent.com/59951991/165039272-04af476d-b7b9-4839-8ab6-8173b516b3a4.png)
Problem: the other gists are filtered out - NOK

2) type (Case-sensitive + Regular expression options ON): perspective 

![image](https://user-images.githubusercontent.com/59951991/165039765-de2e7eec-b56d-42ba-873b-f6244c418b70.png)

Problem: Regular expressions functionality works incorrectly

@ianlethic FYI

**Comment by nadezhday** [comment]
Nadya: I am not sure that users will use this functionality. Do we really need this option?

Normanskaya: important options for them.

**Comment by nadezhday** [comment]
![image](https://user-images.githubusercontent.com/59951991/165042677-b49fbe98-2ce2-4932-96f6-31a46193149f.png)

**Comment by ianlethic** [comment]
Case sensitive + Regular expression work unpredictable, may be allow to work only with one?
Now I turned them on both on ^[a-z]$, so I expected to see only small latin letters in names, but:
<img width="913" alt="image" src="https://user-images.githubusercontent.com/71634843/165062389-25df965c-40f0-4e51-9157-d8bf388fbf42.png">
it show russian letters and also spaces + punctuations..
However even if turned off case-sensitive it also show russian letters:
<img width="702" alt="image" src="https://user-images.githubusercontent.com/71634843/165062592-ac0a6186-c1f7-42c7-be1d-5bedf7b4be80.png">

**Comment by myrix** [comment]
Fixed, now invalid regular expressions are processed correctly:
![image](https://user-images.githubusercontent.com/2802467/165067236-53306d37-1805-48dc-826c-f84bac2057cc.png)

Search works as expected.

In general, the search is for translation gists (groups of translations of the same concept for different locales) as whole units, so the translation gist is returned in the search with all its translations if any of its translations satisfy the search condition.

@nadezhday 

> 1. type: perspective*9
>        ![image](https://user-images.githubusercontent.com/59951991/165039272-04af476d-b7b9-4839-8ab6-8173b516b3a4.png)
>        Problem: the other gists are filtered out - NOK

Works as expected, regular expression "perspective*9" satisfies any of "perspectiv9", "perspective9", "perspectivee9", "perspectiveee9" and so on, with any number of "e"s before 9, so the only returned result in the search is expected.

If you wish to search for anything with "9" after "perspective" in it, so that the search would have "perspective8329" and "perspective0973" in it, use "perspective.*9" regexp, with dot "." allowing any characters.

> 2. type (Case-sensitive + Regular expression options ON): perspective 
> ![image](https://user-images.githubusercontent.com/59951991/165039765-de2e7eec-b56d-42ba-873b-f6244c418b70.png)
> Problem: Regular expressions functionality works incorrectly

As expected, returns any translation gist which has at least one translation with exactly "perspective" in it.

@ianlethic 

> Case sensitive + Regular expression work unpredictable, may be allow to work only with one? Now I turned them on both on ^[a-z]$, so I expected to see only small latin letters in names, but: <img alt="image" width="913" src="https://user-images.githubusercontent.com/71634843/165062389-25df965c-40f0-4e51-9157-d8bf388fbf42.png"> it show russian letters and also spaces + punctuations.

As expected, returns any translation gist which has at least one translation consisting of any number lower-case latin letters in it, including of none, so the search is satisfied by empty translations.

If you wish to search for translation gists which have at least one only lower-case latin letter translation, use necessary non-empty regexp "^[a-z]+$".

> However even if turned off case-sensitive it also show russian letters: <img alt="image" width="702" src="https://user-images.githubusercontent.com/71634843/165062592-ac0a6186-c1f7-42c7-be1d-5bedf7b4be80.png">

As expected, returns any translation gist which has at least one empty or fully latin-letter translation.

**Comment by nadezhday** [comment]
Verified.
Covered in tests\test_tools_translations.py
