### ISSUE TITLE
Translation: search does not work properly

### ISSUE THREAD

**Issue by nadezhday** [ispras/lingvodoc-react#756]
Problem found during verification https://github.com/ispras/lingvodoc-react/issues/562

login as admin
http://83.149.198.62/edit_translations
all
search for: Dictionary
Result: entries found - OK
![image](https://user-images.githubusercontent.com/59951991/168008351-e1be4aee-65aa-4de9-a712-6fdbb225e06a.png)

click any page (33)
![image](https://user-images.githubusercontent.com/59951991/168008925-57997cc7-a121-407d-84e3-450e78053e17.png)

search for: Narym dialect. Dictionary of the Selkup monument "Материалы для ознакомления с наречием остяков Нарымского края" by St. Macarius (Nevsky) (1884).

Problem: item is not found - NOK
![image](https://user-images.githubusercontent.com/59951991/168009050-257ceee6-38cd-4a7d-8ab5-490918c923c4.png)

**Comment by myrix** [comment]
Fixed, now as expected shows 1 translation item the search was for.

**Comment by nadezhday** [comment]
Video:
[2022-05-16 13-21-53.zip](https://github.com/ispras/lingvodoc-react/files/8699243/2022-05-16.13-21-53.zip)

Search for: Narym dialect. Dictionary of the Selkup monument "Материалы для ознакомления с наречием остяков Нарымского края" by St. Macarius (Nevsky) (1884).

Problem: search cannot find the translation gist.

@myrix FYI.

**Comment by myrix** [comment]
Looks like the problem with searching by copying from the header in that case is that it modifies translation by collapsing whitespace, making the header not a valid search string for the translation.

Interestingly, the text area for editing translation, while still showing the translation with collapsed whitespace, actually allows copying translation from it unmodified, and so is a valid source of a search string even in that case.

It's better if the header could also be a source of a valid search string, and if both the header and the text area would show translation as it is without collapsing white space, so that the user may notice and correct anything like doubled spaces or spurious new lines.

**Comment by myrix** [comment]
Implemented, now both the header and translation text area display translations as they are, without collapsing white space, and can both be a valid search string source:
![image](https://user-images.githubusercontent.com/2802467/168689335-ff65a23e-cf66-40a1-8d2f-0294be6b7038.png)

**Comment by nadezhday** [comment]
Narym dialect. Dictionary of the Selkup monument  "Материалы для ознакомления с наречием остяков Нарымского края" by St. Macarius (Nevsky) (1884).
Works fine.

**Comment by vmonakhov** [comment]
Covered in tests/test_tools_translations.py
