### ISSUE TITLE
Proper logging for multiple gunicorn backend's workers

### ISSUE THREAD

**Issue by myrix** [ispras/lingvodoc-react#829]
Currently gunicorn backend's logs are messed up due to each worker being a separate long-running process, all the log files of the rotation (`ld.log`, `ld.log.1`, ..., `ld.log.8`) are being updated simultaneously and, it looks like, not all log messages from all of 32 backend workers are actually being logged.

This is a known problem, see https://github.com/python/cpython/issues/73187.

We should make it so that logging is properly performed to a single log file, which would be properly rotated as required. It's better in general and important for when we are trying make sense of non-obvious  backend problems happening on production server in particular.

**Comment by vmonakhov** [comment]
Fixed using the pip:

`concurrent_log_handler==0.9.24`

From docker.ini:

```
[handler_filelog]
class = concurrent_log_handler.ConcurrentRotatingFileHandler
args = ('/tmp/ld.log', 'a', 16777216, 4)
...

[formatter_generic]
format = [%(process)d] %(asctime)s %(levelname)-5.5s [%(name)s][%(threadName)s] %(message)s
```
 
Created graphql request to reproduce the issue and to test the solution. In order to call it use the following with curl:
```
... --data-raw '{"operationName":"fillLogs","variables":{"worker":1},"query":"query fillLogs($worker: Int) {fill_logs(worker: $worker)}"}'
```
worker can get various id (worker == 1 above)

Now all the parallel workers write self logs to common file and this log file is rotated properly.

**Comment by vmonakhov** [comment]
Resolved.
