### ISSUE TITLE
/map_search: empty block in AND/OR condition  -> Search hangs up

### ISSUE THREAD

**Issue by vmonakhov** [ispras/lingvodoc-react#940]
/map_search:
> type some word to search, add OR block and type some word there, click Search ->OK

![2023-02-08_14-40-50 (2)](https://user-images.githubusercontent.com/18721530/217524205-f1fbe71f-2fc9-4cae-b49a-9e2fdcca22b1.png)

> click [x] to remove condition from the second OR block, leave the second OR block empty, click Search -> Hangs up (at all)

![2023-02-08_15-11-01](https://user-images.githubusercontent.com/18721530/217526922-d3f941d8-f1f5-49e0-8ea6-4704b0104119.png)

> Note that the single empty OR block does not lead to hanging up.

![2023-02-08_15-05-05](https://user-images.githubusercontent.com/18721530/217525697-950f8284-9c5a-485b-a204-cfba371f4e16.png)

> The same is valid for AND mode (empty non-single AND block)

**Comment by myrix** [comment]
Fixed by adding a check for an empty AND block in OR mode.

**Comment by vmonakhov** [comment]
To reopen.

/map_search
Choose AND mode
Remove OR block within the AND one

![2023-04-07_20-42-40 (3)](https://user-images.githubusercontent.com/18721530/230654717-13365be8-27d2-4705-8584-a27ae6bafd32.png)

Or even remove the AND block itself

![2023-04-07_20-43-03 (2)](https://user-images.githubusercontent.com/18721530/230654725-49f99db9-9ed7-4165-b088-f30e7d24f206.png)

Press Search and wait for result (the page hangs up):

![2023-04-07_20-50-28](https://user-images.githubusercontent.com/18721530/230654728-36975258-6af1-4f51-b276-25a28a30a98a.png)

**Comment by myrix** [comment]
Fixed in AND mode too.

Backend now processes both empty OR block and no OR blocks at all correctly.

Frontend does not empty OR block:
![image](https://user-images.githubusercontent.com/2802467/230748141-5406dba5-8d6f-475b-8dc1-60d8e2026b1a.png)

Search without any conditions in AND mode returns no results:
![image](https://user-images.githubusercontent.com/2802467/230748155-d1808aaf-e7cb-4efa-9ab8-c7c506ae5f79.png)

**Comment by vmonakhov** [comment]
I'm very sorry... but...
AND mode:

![2023-04-10_20-15-35](https://user-images.githubusercontent.com/18721530/230955198-892ac7b9-2bc2-4129-b63b-5aeda7274511.png)

Press Search:

![2023-04-10_20-11-34](https://user-images.githubusercontent.com/18721530/230955227-644d6e0d-7611-4b11-ae53-f03dcd82cc00.png)

**Comment by myrix** [comment]
> I'm very sorry... but...

Error discovery is very good, shows us what does not work and gives us opportunity to fix it. Otherwise there will be parts of the system not working with us none the wiser, which is obviously bad. So the more (high-quality, reproducible) error reports, the better!

Fixed, simultaneously discovered that 'Ignore diacritics' option (#415) does not work in AND mode, fixed that too.

**Comment by vmonakhov** [comment]
Everything works good. Verified.

**Comment by vmonakhov** [comment]
All the cases are covered in tests/test_tools_search_03.py
